export const PathName = {
  home: 'HomeScreen',
  login: 'LoginScreen',
  register: 'RegisterScreen',
  listProduct: 'ListProductScreen',
  details: 'DetailsScreen',
  cart: 'CartScreen',
  profile: 'ProfileScreen',
  checkout: 'CheckoutScreen',
  stackHomeNavigate: 'StackHomeNavigate',
  stackCartNavigate: 'StackCartNavigate',
  stackProfileNavigate: 'StackProfileNavigate',
  myOrders: 'MyOrders',
  settings: 'Settings',
};
